algoritmo "semnome"
var
   numero1, numero2: inteiro
inicio
   escreval(" ---------------------")
   escreval("    HORA DA EQUACAO   ")
   escreval(" ---------------------")
   
   escreva("digite um numero: ")
   leia(numero1)
   escreva("digite outro numero: ")
   leia(numero2)
   
   se( numero1 < numero2) entao
     escreva("o 1º numero é o menor.")
   senao
     escreva("o 2º numero é o menor.")
   fimse
fimalgoritmo